[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  node_version = "18"

# API → Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# Short link slugs → redirect function (must be before SPA catch-all)
[[redirects]]
  from = "/:slug"
  to   = "/.netlify/functions/redirect/:slug"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
